name: Daily Update

on:
  schedule:
    - cron: '00 11 * * *'
  workflow_dispatch:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'



    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python script
      run: python tt.py

    - name: 提交更改
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit tv.txt -m "Add generated file"
        git push -f
